
version: '3'

services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      args:
        DJANGO_ALLOWED_HOSTS: '*'
        DJANGO_SECRET_KEY: '*'
        DJANGO_CORS_ORIGIN_WHITELIST: '*'
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "python3 manage.py makemigrations &&
                    python3 manage.py migrate &&
                    python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - database
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/frontend
      - ./frontend/node_modules
    ports:
       - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - static_volume:/backend/static
      - build_folder:/var/www/frontend
    depends_on:
      - backend
      - frontend
      - database
volumes:
  build_folder:
  postgres_data:
  frontend:
  static_volume:
  backend:
