
version: '3'

services:
  backend:
    build:
      context: ./backend/project/
      args:
        DJANGO_ALLOWED_HOSTS: '*'
        DJANGO_SECRET_KEY: '*'
        DJANGO_CORS_ORIGIN_WHITELIST: '*'
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
       - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./webserver/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - build_folder:/var/www/frontend
    depends_on:
      - backend
      - frontend
volumes:
  build_folder:
