
version: '3'

services:
  backend:
    build:
      context: ./fourohfour_backend
      args:
        DJANGO_ALLOWED_HOSTS: '*'
        DJANGO_SECRET_KEY: '*'
        DJANGO_CORS_ORIGIN_WHITELIST: '*'
    command: gunicorn fourohfour_backend.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./fourohfour_frontend
    volumes:
      - build_folder:/frontend/build
    ports: 
       - "3000:3000"
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./webserver/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - build_folder:/var/www/frontend
    depends_on:
      - backend
      - frontend
volumes:
  build_folder: